### ISSUE TITLE
TypeError when using Freemarker variables in JS code

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-source-formatter#22]
This freemarker code leads to a Type Error: 

`<script type="text/javascript">
	var OSBForm${article_namespace};
</script>`

Unhandled rejection TypeError: Cannot read property 'type' of null
    at collectedReport.forEach (/Users/allenziegenfus/.nvm/versions/node/v6.4.0/lib/node_modules/check-source-formatting/lib/lint_js_rules/no_unused_vars.js:58:72)

**Comment by natecavanaugh** [comment]
Thanks @allen-ziegenfus ,
I'm gonna check this one out and I'll push up a fix as soon as possible :)
