### ISSUE TITLE
Request invalid order inside aui:script taglib

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#24]
For `aui:script` `require` attribute  we can specify the dependency name that will be used inside the tag like:

`<aui:script require="metal-dom/src/all/dom as dom">`

source-format produces an error:

`> Sort attribute values: metal-dom/src/all/dom as`

and requires it to be sorted as:

`<aui:script require="as dom metal-dom/src/all/dom">`

which is actually an invalid syntax.

/cc @jbalsas

**Comment by natecavanaugh** [comment]
Hi @p2kmgcl 
Thanks for submitting this. I think can add this to the list of exclusions for attributes to ignore for sorting (since I'm already doing this for attributes that have a `javascript:` protocol executing).
I can go ahead and start working on that :)

Thanks again for the report!
