### ISSUE TITLE
Recognizes inner attributes as outer attributes throws formatting errors for sorting attributes

### ISSUE THREAD

**Issue by jotchon** [liferay/liferay-frontend-source-formatter#25]
**Example:**
<a class="${logo_css_class}" href="${site_default_url}" **title="<@language_format arguments="${site_name}" key="go-to-x" />"**>

**Thrown Error:** Sort attributes for "title" and "key", but "key" does not belong to <a>

**Possible cause:** Under "title" attribute, the attributes for language_format element is recognized as attributes in the <a> element.

**Comment by drewbrokke** [comment]
Closing based on our discussion.  New issue filed here: https://github.com/liferay/liferay-frontend-source-formatter/issues/25.

**Comment by natecavanaugh** [comment]
Hi @jotchon 
Thanks for posting this, but if you look in the README file, you'll see this listed under the [Known Issues section](https://github.com/liferay/liferay-frontend-source-formatter/blob/master/README.md#known-issues).

I'll leave this open for a little bit, in case anyone has any ideas about how to go about fixing it, but I have yet to find a way.

Here's how the script currently handles it, and why it has an issue with this.

For handling HTML formatting, I have to use the [worst possible approach](https://stackoverflow.com/a/1732454) to parsing HTML, which is to use regular expressions.

We have everything from plain HTML, to JSP's, Velocity, Freemarker, Soy, etc.
So to grab the attributes, I first look for all XML like tags `<[^>]+?>` (look for anything tag like), then within each tag, look for anything like `/^([^=]+)=(["'])(.*)\2$/` (look for anything that looks like `foo="bar"`).

Before parsing, I remove scriptlets and known items that are used in tags, but don't need to be parsed.

The problem with nested tags is that I can remove them before the attribute parsing, but their attributes may need sorting as well.

I have some ideas on how I could possibly handle this, but I'll need some time to see if they can work for both cases.

Thanks again for filing :)

**Comment by natecavanaugh** [comment]
Nothing has panned out for this, so I'm going to close it for now, until I can find a workable solution :)
