### ISSUE TITLE
Variables imported with aui:script are not defined

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#27]
When any library is being imported inside an aui:script, the formater reports the library as undefined, and gives "'something' is not defined" warning. Here you have a sample:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/select_basic_pages.jsp#L86-L87

In those lines metal-dom is imported as `dom`, and being used in the next line, but csf returns "'dom' is not defined" as message error.

**Comment by natecavanaugh** [comment]
Heya Pablo, sorry for the delay on this, but thanks for reporting this. This should be fixed now, and once Travis passes, I'll release a new version for this :)

Thanks again!
