### ISSUE TITLE
Throwing "Sort  variables" warning when it shouldn't

### ISSUE THREAD

**Issue by protoEvangelion** [liferay/liferay-frontend-source-formatter#28]
Within an `.ftl` file, inside a `<script></script>`  I have code that looks like this:

```js
var svgWidth = 100;
var circleWidth = svgWidth * 2;
```

It throws this warning:

```
Line 71: Sort variables: svgWidth circleWidth
```

Because `circleWidth` uses `svgWidth` it should not throw this error. It throws this same error for many other variables that are technically not sorted but can't be because they consume one another.

@natecavanaugh _Are there any workarounds for this or would this be considered a bug?_

**Comment by jbalsas** [comment]
Hey @protoEvangelion, the convention is that definition blocks should be sorted, as order should not matter. When it does, as in this case, we add blank line between both of them, which will remove the warning and show that those lines need to stay in that specific order.

Hope that helps! :)

**Comment by natecavanaugh** [comment]
Hey guys, sorry for the delay, but I should be able to check if the variable that's out of order is using a previous variable, and modify the message accordingly. I know I [do this for constants](https://github.com/liferay/liferay-frontend-source-formatter/blob/master/test/lint_js_rules/sort_constants.js#L19) (though as long as the line spacing is maintained, there's no need for me to change the message).
I'll leave this open until I can add this in.

Thanks guys!
