### ISSUE TITLE
SF fails with "try" string and break methods in .js files

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/liferay-frontend-source-formatter#34]
Source format scripts break some methods in JS files when there is a "try" string present. 
Please check the first two commits in this PR: https://github.com/brianchandotcom/liferay-portal/pull/66849.
There might be an issue around https://github.com/liferay/liferay-frontend-source-formatter/blob/1816e62b295773dd7c0b3da68f8ce218f2d76b1a/lib/engine_rules/js.js#L61

**Comment by bryceosterhaus** [comment]
Fixed in `2.0.14`
