### ISSUE TITLE
Enforce/disallow HTML void tags' slash

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#43]
Since HTML5, we do not need to add an ending slash in void HTML tags. In JSX we do need to add them, as they are required by the compiler, but in Soy we should either enforce or disallow using them:

Invalid
```
<img src="" />
<input type="text">
```

Valid
```
<img src="">
<input type="text">

or

<img src="" />
<input type="text" />
```

**Comment by natecavanaugh** [comment]
Personally, I think we should enforce them for self closing tags, but do you have an example of how we could possibly enforce this? Parsing this just on Soy files would be a pretty big undertaking, but I'm not sure how we'd be able to apply it to any other HTML (specifically JSP's) without some intense regex parsing (and even then, it'd probably be pretty fragile).

**Comment by wincent** [comment]
We're [going to be archiving this project](https://github.com/liferay/liferay-frontend-source-formatter/pull/58#issuecomment-687057235) so closing everything.
