### ISSUE TITLE
Explanation for "Block level containers need either a class or id"

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#44]
I've found myself with some errors saying I should add a class or id to block level containers, like this one:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/input_asset_links/page.jsp#L77

Can someone give me some clarification of why should I do this? I don't want to add random id/classes to block elements. Should I try to remove them?

**Comment by jbalsas** [comment]
Hey @p2kmgcl, I'm not sure about this one myself... I'd guess the rationale behind this is that if you're not adding an `id` so you can refer to the block nor a class so you can style the contents... what purpose does that anonymous block really serve?

Just my thoughts... @natecavanaugh should know more.

**Comment by p2kmgcl** [comment]
@jbalsas mmm maybe that was not a good example. But anyway, having some explanation would be nice, just to be sure what should I fix :smile:

**Comment by natecavanaugh** [comment]
Hey guys, sorry for the delay, but this might be worth reading :) https://github.com/liferay/liferay-frontend-source-formatter/wiki#anonymous-block-containers

I don't publish the link often enough, as I was planning on filling it out more, but it's got quite a bit of info already :)

**Comment by p2kmgcl** [comment]
@natecavanaugh I just realised the wiki exists :sweat_smile:
