### ISSUE TITLE
Wrap JSDoc comments to 80 columns

### ISSUE THREAD

**Issue by codyhoag** [liferay/liferay-frontend-source-formatter#45]
We currently have to manually wrap JSDoc comments to follow our 80 column wrapping rule. It would be very useful (and time saving) if the tool could enforce this wrapping automatically.

**Comment by wincent** [comment]
Correctly wrapping comments is pretty hard, if [this two-year-old Prettier ticket is anything to judge by](https://github.com/prettier/prettier/issues/265); should definitely take some of the "gotchas" mentioned in that ticket into account.

**Comment by codyhoag** [comment]
Our [Javadoc Formatter](https://github.com/liferay/liferay-portal/blob/master/modules/util/javadoc-formatter/src/main/java/com/liferay/javadoc/formatter/JavadocFormatter.java) does it fairly well. Perhaps we could do something similar to what's done for Javadoc?

**Comment by pauldraper** [comment]
Prettier has prose wrapping in Markdown too.

It think it's mostly a matter of (a) having it opt-in (b) making sure there is a code-local ignore (c) only formatting block comments.

**Comment by wincent** [comment]
We're [going to be archiving this project](https://github.com/liferay/liferay-frontend-source-formatter/pull/58#issuecomment-687057235) so closing everything.
