### ISSUE TITLE
Running the source formatter breaks some functions calls

### ISSUE THREAD

**Issue by andresfulla** [liferay/liferay-frontend-source-formatter#46]
So, my code is:
```javascript
this._selectAssetEntry(selectedAssetEntry);
```

and the reformatted code I get is

```javascript
this._selectAssetEn tryselectedAssetEntry);
```

which is invalid Javascript syntax. My bet is this happens because of the `try` in the function name.

**Comment by natecavanaugh** [comment]
I believe this is fixed in the latest version. Can you state which version of the formatter you're on?

**Comment by andresfulla** [comment]
We are consuming the formatter via `liferay-npm-scripts`. We updated it and it no happens. Thanks!!!
