### ISSUE TITLE
Force/disallow new line when chaining 

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#47]
Yesterday I had this issue while declaring a property in a metal component:

https://github.com/brianchandotcom/liferay-portal/pull/70013#issuecomment-476393682

I am not sure if we should add new lines for each Config method or chain everything in a single line, and formatSource gives no feedback about this.

I think prettier (#33) measures the length of the line and/or the number of method calls and adds/removes new lines depending on the situation. Do we have strict rules (like prettier does) for this situation?

This are some issues addressed by prettier for chaining:

- https://github.com/prettier/prettier/issues/3951
- https://github.com/prettier/prettier/issues/1565
- https://github.com/prettier/prettier/issues/1282

And a sample of how it is formatted: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBhCBbADtBMB0AygCoCCxAogAQC8VwAOlFVVgE4RalJXpQBmASwDm+QbDhsoAQwA2ACgCU+AM4w244UvwA3OQFc48gOSljigDRMmLdpwBCPPkOE2qDAuPhS5Stx9V1TT9mdwI9WUMTe3MrKDc7LFQnaBdAjSgtZQio41RY-1DEgBEUgRF-TwkfBUVK3QMjY2KCqABfEAsQThhBaBVkUGk2DgB3AAVhhAGUaR0IQQATTpAAIzZpMABrOBhCLE3NZHVDLoALGAxZAHUzwXgVA7A4Qmn7wR17gE9kcBUBrriFSSGDjDbCDDSZD8OTAroAKxUAA97BttrtCNIMHAADLiODQ2FwBHIwiaWRwACK+gg8EJsjhIAObGBbF+q2kqy+smgK3YXmuSxgZ2QAA4AAxdOzA64bLC-dhwVk6AldNhwACO+kE6rB0ghUKQMIZxJAwIwgmObFOZvJVJpdKQJ1NME5gsWwuQABYuuppIJZJp0BhIb8oLgVvpgcROTNnW02kA

/cc @jbalsas

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
